/**
 * Better Editor live data-source widgets.
 *
 * The legacy Appearance Center and non-Better widgets were removed. This
 * registry intentionally exposes only the widget types rendered by /editor.
 */
import { registerWidget } from "./widgetRegistry";

import BackgroundConfig from "./background/BackgroundConfig";
import BackgroundWidget from "./background/BackgroundWidget";
import BetsConfig from "./bets/BetsConfig";
import BetsWidget from "./bets/BetsWidget";
import BonusHuntConfig from "./bonus-hunt/BonusHuntConfig";
import BonusHuntWidget from "./bonus-hunt/BonusHuntWidget";
import ChatConfig from "./chat/ChatConfig";
import ChatWidget from "./chat/ChatWidget";
import ConnectFourConfig from "./connect-four/ConnectFourConfig";
import ConnectFourWidget from "./connect-four/ConnectFourWidget";
import GiveawayConfig from "./giveaway/GiveawayConfig";
import GiveawayWidget from "./giveaway/GiveawayWidget";
import NavbarConfig from "./navbar/NavbarConfig";
import NavbarWidget from "./navbar/NavbarWidget";
import RtpStatsConfig from "./rtp-stats/RtpStatsConfig";
import RtpStatsWidget from "./rtp-stats/RtpStatsWidget";
import SlideshowFrameWidget from "./slideshow-frame/SlideshowFrameWidget";
import TournamentConfig from "./tournament/TournamentConfig";
import TournamentWidget from "./tournament/TournamentWidget";
import RaidShoutoutConfig from "./raid-shoutout/RaidShoutoutConfig";
import RaidShoutoutWidget from "./raid-shoutout/RaidShoutoutWidget";

const CURRENCY = "EUR ";

registerWidget({
  type: "connect_four",
  label: "Chat Connect 4",
  icon: "4",
  description:
    "Run two-player Twitch chat matches with StreamElements point wagers.",
  category: "better",
  component: ConnectFourWidget,
  configPanel: ConnectFourConfig,
  styleConfigKey: "displayStyle",
  styles: [
    {
      id: "chat_connect_four",
      icon: "4",
      label: "Chat Connect 4",
      defaultSize: { width: 620, height: 790 },
    },
  ],
  defaults: {
    displayStyle: "chat_connect_four",
    title: "CHAT CONNECT 4",
    playerOneColor: "#ef4444",
    playerTwoColor: "#facc15",
    boardColor: "#1e3a8a",
    boardBorderColor: "#1e3a8a",
    titleColor: "#fbbf24",
    textColor: "#f7fbff",
    mutedColor: "#fff2b8",
    fontFamily: "'Rajdhani', sans-serif",
    fontScale: 100,
    showWager: true,
    showPlayers: true,
    showCommandHelp: true,
    showMoveCount: true,
    showTurnTimer: true,
    animateDrops: true,
    chatCommand: "!connect4",
    twitchChannel: "",
  },
});

registerWidget({
  type: "raid_shoutout",
  label: "Twitch Shoutout",
  icon: "📣",
  description:
    "Play a Twitch clip when the channel owner or a moderator uses !so username.",
  category: "better",
  component: RaidShoutoutWidget,
  configPanel: RaidShoutoutConfig,
  styleConfigKey: "displayStyle",
  styles: [
    { id: "better_raid_shoutout", icon: "📣", label: "Twitch Shoutout" },
  ],
  defaults: {
    displayStyle: "better_raid_shoutout",
    twitchChannel: "",
    chatCommandEnabled: true,
  },
});

registerWidget({
  type: "bonus_hunt",
  label: "Better Hunt",
  icon: "🎯",
  description: "Live bonus hunt data used by the Better Editor widget.",
  category: "better",
  component: BonusHuntWidget,
  configPanel: BonusHuntConfig,
  styleConfigKey: "displayStyle",
  styles: [{ id: "better_bonus_hunt", icon: "🎯", label: "Better Hunt" }],
  defaults: {
    displayStyle: "better_bonus_hunt",
    bonuses: [],
    requests: [],
    huntActive: false,
    openingMode: false,
    currency: CURRENCY,
    startMoney: 0,
    targetMoney: 0,
    stopLoss: 0,
    showStatistics: true,
    animatedTracker: true,
    drawerMode: "contain",
    drawerRevealSeconds: 30,
    drawerHoldSeconds: 15,
    colour: "ocean",
    finish: "flat",
    skin: "modern",
    fontFamily: "'Rajdhani', sans-serif",
    edgeRadius: 14,
    statRadius: 7,
    headerAccent: "#20d8ff",
    accentColor: "#20d8ff",
    headerColor: "#061126",
    bgColor: "#061126",
    listCardColor: "rgba(32,216,255,0.07)",
  },
});

registerWidget({
  type: "giveaway",
  label: "Better Giveaway",
  icon: "🎁",
  description:
    "Live giveaway entries and winner data used by the Better Editor widget.",
  category: "better",
  component: GiveawayWidget,
  configPanel: GiveawayConfig,
  styleConfigKey: "displayStyle",
  styles: [{ id: "better_giveaway", icon: "🎁", label: "Better Giveaway" }],
  defaults: {
    displayStyle: "better_giveaway",
    title: "",
    prize: "",
    keyword: "",
    isActive: false,
    winner: "",
    participants: [],
    twitchEnabled: false,
    twitchChannel: "",
    kickEnabled: false,
    kickChannelId: "",
    surface: "matte",
    hue: 195,
    hueShift: 10,
    saturation: 88,
    lightness: 7,
    accentSat: 96,
    accentLight: 58,
    panelHi: "#0c1c40",
    panelLo: "#081228",
    cardHi: "#0d2049",
    cardLo: "#0a1836",
    lineColor: "#2f63c9",
    accentColor: "#45c8ff",
    deepAccentColor: "#1e5ad6",
    bgColor: "#0a1734",
    textColor: "#eef6ff",
    mutedColor: "#6d8cc4",
    secondaryTextColor: "#9dbdf2",
    glow: 30,
    innerGlow: 35,
    textGlow: 30,
  },
});

registerWidget({
  type: "navbar",
  label: "Better Navbar",
  icon: "🧭",
  description:
    "Streamer identity, Spotify, socials, and status data used by the Better Editor navbar.",
  category: "better",
  component: NavbarWidget,
  configPanel: NavbarConfig,
  styleConfigKey: "displayStyle",
  styles: [{ id: "better_navbar", icon: "🧭", label: "Better Navbar" }],
  defaults: {
    displayStyle: "better_navbar",
    streamerName: "",
    motto: "",
    showAvatar: true,
    showClock: true,
    showNowPlaying: false,
    showCrypto: false,
    showSocials: false,
    showCTA: false,
    ctaText: "Be Gamble Aware!",
    cryptoCoins: [],
    socialDisplayStyle: "handles",
    kickChannelId: "",
    youtubeChannel: "",
    xUsername: "",
    instagramUsername: "",
    discordUrl: "",
    tiktokUsername: "",
    musicSource: "spotify",
    manualArtist: "",
    manualTrack: "",
    casinoName: "",
    casinoCommand: "!casino",
    accentColor: "#20d8ff",
    accentBlue: "#1385e9",
    accentGold: "#ffb020",
    ctaColor: "#ffb020",
    bgColor: "#061126",
    textColor: "#f8fafc",
    mutedColor: "#8baacf",
    borderWidth: 1,
    borderRadius: 12,
  },
});

registerWidget({
  type: "chat",
  label: "Better Chat",
  icon: "💬",
  description:
    "Live Twitch, YouTube, or Kick chat data used by the Better Editor chat.",
  category: "better",
  component: ChatWidget,
  configPanel: ChatConfig,
  styleConfigKey: "chatStyle",
  styles: [{ id: "better_chat", icon: "💬", label: "Better Chat" }],
  defaults: {
    chatStyle: "better_chat",
    twitchEnabled: true,
    twitchChannel: "",
    youtubeEnabled: false,
    youtubeVideoId: "",
    youtubeApiKey: "",
    kickEnabled: false,
    kickChannelId: "",
    maxMessages: 50,
    showHeader: true,
    showLegend: true,
    showBadges: true,
    useNativeColors: true,
    font: "Arial, Helvetica, sans-serif",
    glow: "#45c8ff",
    username: "#45c8ff",
    text: "#eef6ff",
    bubble: "#0d2049",
    panel: "#0a1734",
    panelHi: "#0c1c40",
    panelLo: "#081228",
    cardLo: "#0a1836",
    borderColor: "#2f63c9",
    showRoleBadges: true,
    roleEffects: {
      enabled: true,
      ownerEnabled: true,
      ownerMovementEnabled: true,
      moderatorEnabled: true,
      moderatorMovementEnabled: true,
      vipEnabled: true,
      vipMovementEnabled: true,
      subscriberEnabled: true,
      subscriberMovementEnabled: true,
      intensity: 8,
      ownerColor: "#ff3b5c",
      moderatorColor: "#22d3ee",
      vipColor: "#c084fc",
      subscriberColor: "#facc15",
      raidColor: "#ff2d8d",
    },
    shoutoutInChat: false,
    shoutoutPosition: "top",
    shoutoutHeight: 180,
    shoutoutDuration: 45,
    shoutoutDismissOnClipEnd: false,
  },
});

registerWidget({
  type: "rtp_stats",
  label: "Better RTP Stats",
  icon: "📖",
  description:
    "Current slot RTP, potential, volatility, and personal best data.",
  category: "better",
  component: RtpStatsWidget,
  configPanel: RtpStatsConfig,
  styleConfigKey: "displayStyle",
  styles: [{ id: "better_rtp", icon: "📖", label: "Better RTP Stats" }],
  defaults: {
    displayStyle: "better_rtp",
    slotName: "",
    provider: "",
    providerLogo: "",
    rtp: "",
    potential: "",
    volatility: "",
    bestWin: "",
    showProvider: true,
    showRtp: true,
    showPotential: true,
    showVolatility: true,
    showBestWin: true,
    cRim: "#1385e9",
    cBarTop: "#0a2140",
    cBarMid: "#07182f",
    cBarBot: "#061126",
    cLabel: "#8baacf",
    cValue: "#ffffff",
    cBolt: "#ffb020",
    cGold: "#ffb020",
    cBrand: "#8baacf",
    cEmA: "#20d8ff",
    cEmB: "#ffb020",
    cEmBase: "#0a1a33",
  },
});

registerWidget({
  type: "background",
  label: "Better Background",
  icon: "🖼️",
  description:
    "Background source and effects used by the Better Editor overlay.",
  category: "better",
  component: BackgroundWidget,
  configPanel: BackgroundConfig,
  styleConfigKey: "displayStyle",
  styles: [{ id: "better_background", icon: "🖼️", label: "Better Background" }],
  defaults: {
    displayStyle: "better_background",
    bgMode: "texture",
    textureType: "gradient",
    color1: "#020611",
    color2: "#1385e9",
    color3: "#20d8ff",
    gradientAngle: 135,
    patternSize: 20,
    animSpeed: 8,
    imageUrl: "",
    videoUrl: "",
    imageFit: "cover",
    imagePosition: "center",
    opacity: 100,
    overlayColor: "#000000",
    overlayOpacity: 0,
  },
});

registerWidget({
  type: "slideshow_frame",
  label: "Slideshow Frame",
  icon: "🎞️",
  description:
    "Image and video slideshow frame used by the Better Editor overlay.",
  category: "better",
  component: SlideshowFrameWidget,
  configPanel: null,
  styleConfigKey: "displayStyle",
  styles: [
    { id: "better_slideshow_frame", icon: "🎞️", label: "Slideshow Frame" },
  ],
  defaults: {
    displayStyle: "better_slideshow_frame",
    mediaText: "",
    frameStyle: "neon",
    frameColor: "#2f63c9",
    accentColor: "#45c8ff",
    backgroundColor: "#0a1734",
    panelHi: "#0c1c40",
    panelLo: "#081228",
    fit: "cover",
    transition: "fade",
    slideMs: 5000,
    transitionMs: 650,
    autoplay: true,
    videoMuted: true,
    videoLoop: true,
    showVideoControls: false,
    showCounter: false,
    radius: 12,
    borderWidth: 1,
    padding: 8,
    glow: 35,
    aspectPreset: "banner",
  },
});

registerWidget({
  type: "bets",
  label: "Better Bets",
  icon: "💎",
  description: "Live chat betting state and StreamElements payout settings.",
  category: "better",
  component: BetsWidget,
  configPanel: BetsConfig,
  styleConfigKey: "displayStyle",
  styles: [{ id: "better_bets", icon: "💎", label: "Better Bets" }],
  defaults: {
    displayStyle: "better_bets",
    gameStatus: "idle",
    question: "Place Your Bets",
    timerSeconds: 600,
    chatCommand: "!bet",
    twitchChannel: "",
    seAnnounce: true,
    betSeEnabled: true,
    betMinAmount: 1,
    betMaxAmount: 0,
    options: [
      { label: "0 - 99" },
      { label: "100 - 199" },
      { label: "200 - 299" },
      { label: "300 - 399" },
      { label: "400 - 499" },
      { label: "500 - 599" },
      { label: "600 - 799" },
      { label: "800 - 999" },
      { label: "1000+" },
    ],
    bets: {},
    betters: {},
    winnerOption: null,
    betsHistory: [],
    bracketHistory: [],
    bracketUsage: [],
    theme: "neon",
    font: "cyber",
    glowIntensity: 62,
    fillStyle: "liquid",
    layoutMode: "cards",
    columns: 2,
    orientation: "vertical",
    cardColors: [
      { accent: "#45c8ff", accent2: "#1e5ad6" },
      { accent: "#2f63c9", accent2: "#4aa0ff" },
      { accent: "#45c8ff", accent2: "#2a55ad" },
      { accent: "#1e5ad6", accent2: "#45c8ff" },
      { accent: "#4aa0ff", accent2: "#2f63c9" },
      { accent: "#2a55ad", accent2: "#45c8ff" },
    ],
  },
});

registerWidget({
  type: "tournament",
  label: "Tournament",
  icon: "🏆",
  description:
    "Create brackets, run matches, and show live tournament standings.",
  category: "better",
  component: TournamentWidget,
  configPanel: TournamentConfig,
  styleConfigKey: "layout",
  styles: [
    { id: "grid", icon: "▦", label: "Grid" },
    { id: "vertical", icon: "↕", label: "Vertical" },
    { id: "minimal", icon: "−", label: "Minimal" },
    { id: "arena", icon: "⚔", label: "Arena" },
    { id: "esports", icon: "🎮", label: "Esports" },
    { id: "scoreboard", icon: "▤", label: "Scoreboard" },
  ],
  defaults: {
    layout: "grid",
    showBg: true,
    panelHi: "#0c1c40",
    bgColor: "#0a1734",
    panelLo: "#081228",
    borderColor: "#2f63c9",
    borderRadius: 20,
    borderWidth: 1,
    mainCardPadding: 14,
    mainShadowColor: "#020617",
    mainShadowBlur: 36,
    mainShadowOpacity: 65,
    mainGlow: 18,
    mainBackdropBlur: 0,
    containerPadding: 8,
    cardGap: 8,
    cardBg: "#0d2049",
    cardBorder: "#2f63c9",
    cardRadius: 14,
    cardBorderWidth: 1,
    nameColor: "#eef6ff",
    multiColor: "#45c8ff",
    slotNameColor: "#6d8cc4",
    nameSize: 16,
    multiSize: 18,
    slotNameSize: 12,
    fontFamily: "'Rajdhani', sans-serif",
    showSlotName: true,
    slotImageRadius: 10,
    swordSize: 24,
    swordColor: "#45c8ff",
    swordBg: "#071022",
    xIconColor: "#ef4444",
    xIconBg: "#1f1420",
    activeStatusColor: "#45c8ff",
    statusBadgeBg: "#0a1836",
    scoreNeutralColor: "#9dbdf2",
    scoreNegativeColor: "#ef4444",
    eliminatedOpacity: 0.35,
    tournamentTitle: "Tournament",
    bracketName: "Tournament",
    bracketType: "bonus_bo3",
    bracketPlayerCount: 8,
    bracketPlayers: [],
    bracketData: [],
    bracketPhase: "setup",
    data: {
      matches: [],
      currentMatchIdx: 0,
    },
  },
});
