export const STANDARD_BETTER_WIDGET_GEOMETRY = Object.freeze({
  background: { x: 0, y: 0, width: 1920, height: 1080, zIndex: 0 },
  tournament: {
    x: 4,
    y: 69.36370849609375,
    width: 960,
    height: 720,
    zIndex: 28,
  },
  navbar: { x: 0, y: 0, width: 1915, height: 72, zIndex: 10 },
  rtp_stats: {
    x: 331.1822509765625,
    y: 760.54541015625,
    width: 1245,
    height: 57,
    zIndex: 20,
  },
  slideshow_frame: {
    x: 1580.5455932617188,
    y: 64.45452880859375,
    width: 336,
    height: 227,
    zIndex: 25,
  },
  bonus_hunt: { x: -18, y: 49, width: 369, height: 884, zIndex: 30 },
  bets: { x: 260, y: 800, width: 778, height: 300, zIndex: 40 },
  chat: {
    x: 1580.5455932617188,
    y: 313.5455322265625,
    width: 218,
    height: 457,
    zIndex: 50,
  },
  giveaway: {
    x: 1557.7272338867188,
    y: 800,
    width: 420,
    height: 270,
    zIndex: 60,
  },
  connect_four: { x: 650, y: 135, width: 620, height: 790, zIndex: 65 },
  raid_shoutout: { x: 640, y: 360, width: 640, height: 360, zIndex: 70 },
});

export const STANDARD_BETTER_WIDGET_CONTROLS = Object.freeze({
  connect_four: {},
  raid_shoutout: {
    displayStyle: "better_raid_shoutout",
    frameStyle: "neon",
    animation: "slide-left",
    displayDuration: 45,
    showStreamerInfo: true,
    showClipTitle: true,
    showViews: true,
    showTimer: true,
    showFooter: true,
    showCornerDots: true,
    showScanline: true,
    autoplay: true,
    muted: true,
    dismissOnClipEnd: false,
    twitchChannel: "",
    chatCommandEnabled: true,
    headingText: "Shoutout",
    accentColor: "#45c8ff",
    secondaryColor: "#1385e9",
    backgroundColor: "#081228",
    textColor: "#ffffff",
    mutedColor: "#8baacf",
    borderRadius: 12,
    borderWidth: 1,
    glowIntensity: 35,
    avatarSize: 44,
    titleSize: 16,
    subtitleSize: 12,
    fontFamily: "'Rajdhani', sans-serif",
  },
  tournament: {
    layout: "grid",
    showBg: true,
    panelHi: "#0c1c40",
    bgColor: "#061126",
    panelLo: "#081228",
    borderColor: "#1385e9",
    borderRadius: 20,
    borderWidth: 1,
    mainCardPadding: 14,
    mainShadowColor: "#020617",
    mainShadowBlur: 36,
    mainShadowOpacity: 65,
    mainGlow: 18,
    mainBackdropBlur: 0,
    containerPadding: 8,
    cardGap: 8,
    cardBg: "#0a1a33",
    cardBorder: "#1d4f73",
    cardRadius: 14,
    cardBorderWidth: 1,
    nameColor: "#f8fafc",
    multiColor: "#20d8ff",
    slotNameColor: "#8baacf",
    nameSize: 16,
    multiSize: 18,
    slotNameSize: 12,
    fontFamily: "'Rajdhani', sans-serif",
    showSlotName: true,
    slotImageRadius: 10,
    swordSize: 24,
    swordColor: "#20d8ff",
    swordBg: "#0f2138",
    xIconColor: "#ef4444",
    xIconBg: "#1f1420",
    activeStatusColor: "#20d8ff",
    statusBadgeBg: "#10243d",
    scoreNeutralColor: "#94a3b8",
    scoreNegativeColor: "#ef4444",
    eliminatedOpacity: 0.35,
    tournamentTitle: "Tournament",
    bracketName: "Tournament",
    bracketType: "bonus_bo3",
    bracketPlayerCount: 8,
    bracketPlayers: [],
    bracketData: [],
    bracketPhase: "setup",
    data: { matches: [], currentMatchIdx: 0 },
  },
  bonus_hunt: {
    displayStyle: "better_bonus_hunt",
    colour: "ocean",
    finish: "flat",
    skin: "modern",
    orientation: "vertical",
    sessionState: "hunt",
    carouselMode: "3d",
    listMode: "image",
    drawerMode: "expand",
    drawerRevealSeconds: 60,
    drawerHoldSeconds: 30,
    statsLayout: "grid",
    showRequests: true,
    animations: true,
    animSpeed: 0.5,
    carouselMs: 6000,
    font: "orbitron",
    fontFamily: "'Orbitron', sans-serif",
    uiScale: 1.2,
    barHeight: 6,
    avatarSize: 28,
    visibleRows: 3,
    widgetWidth: 0,
    widgetHeight: 0,
    edgeRadius: 14,
    statRadius: 7,
    panelWidth: 402,
    panelHeight: 0,
    radius: 14,
    headerAccent: "#45c8ff",
    accentColor: "#45c8ff",
    headerColor: "#081228",
    bgColor: "#081228",
    listCardColor: "rgba(32,216,255,0.07)",
    cardRadius: 14,
    fontSize: 13,
  },
  giveaway: {
    displayStyle: "better_giveaway",
    title: "Giveaway #1",
    prize: "10$ MBway",
    subtitle: "(min 30 Participants)",
    keyword: "iseca",
    surface: "matte",
    hue: 210,
    hueShift: 24,
    saturation: 82,
    lightness: 7,
    accentSat: 100,
    accentLight: 56,
    panelHi: "#0c1c40",
    panelLo: "#081228",
    cardHi: "#0d2049",
    cardLo: "#0a1836",
    lineColor: "#2f63c9",
    accentColor: "#20d8ff",
    deepAccentColor: "#1e5ad6",
    bgColor: "#061126",
    textColor: "#f8fafc",
    mutedColor: "#8baacf",
    secondaryTextColor: "#9dbdf2",
    width: 420,
    height: 270,
    padX: 31,
    padY: 22,
    tileGap: 12,
    radius: 12,
    borderRadius: 12,
    borderWidth: 3,
    borderAlpha: 0.9,
    tileRadius: 40,
    innerFrame: false,
    innerInset: 2,
    brackets: false,
    bracketSize: 27,
    bracketWidth: 2,
    edgeLights: false,
    sideDashes: false,
    sheen: true,
    glow: 160,
    innerGlow: 160,
    titleFont: "orbitron",
    bodyFont: "rajdhani",
    fontFamily: "'Rajdhani', sans-serif",
    titleSize: 26,
    prizeSize: 14,
    subSize: 15,
    labelSize: 18,
    valueSize: 13,
    titleWeight: 700,
    letterSpacing: 0,
    textGlow: 197,
    italicPrize: true,
    uppercaseLabels: true,
  },
  navbar: {
    displayStyle: "better_navbar",
    streamerName: "BRUTUSPOLUS",
    twitchUsername: "",
    kickChannelId: "",
    youtubeChannel: "",
    avatarUrl: "",
    motto: "www.brutuspolus.com",
    brandName: "",
    siteUrl: "",
    showAvatar: true,
    showClock: true,
    showNowPlaying: true,
    showCTA: true,
    showCasino: false,
    showStartBalance: true,
    showCrypto: true,
    showSocials: true,
    ctaText: "Be Gamble Aware!",
    ctaColor: "#193265",
    startLabel: "Start",
    startValue: "€2000",
    startBalance: 2000,
    balanceCurrency: "€",
    casinoName: "",
    casinoCommand: "!Casino",
    casinoLogoUrl: "",
    casinoImageSize: 100,
    nowPlayingLabel: "Now Playing",
    musicSource: "spotify",
    musicDisplayStyle: "equalizer",
    spotifyWidth: 260,
    cryptoDisplayMode: "horizontal",
    socialDisplayStyle: "handles",
    sectionLayout: [
      { id: "identity", zone: "left" },
      { id: "badge", zone: "left" },
      { id: "clock", zone: "center" },
      { id: "nowPlaying", zone: "right" },
      { id: "crypto", zone: "left" },
      { id: "socials", zone: "right" },
      { id: "cta", zone: "right" },
      { id: "balance", zone: "left" },
      { id: "casino", zone: "left" },
    ],
    xUsername: "",
    instagramUsername: "",
    discordUrl: "",
    tiktokUsername: "",
    accentColor: "#20d8ff",
    accentBlue: "#1385e9",
    accentGold: "#ffb020",
    bgColor: "#061126",
    textColor: "#f8fafc",
    mutedColor: "#8baacf",
    barHeight: 52,
    borderWidth: 1,
    borderRadius: 12,
    radius: 12,
    maxWidth: 1920,
    betterNavbarOptionalCasinoCommandInitialized: true,
    betterNavbarManualCasinoCommand: true,
    betterNavbarFeaturesInitialized: true,
    betterNavbarSpotifyOnlyInitialized: true,
    betterNavbarOptionalCasinoInitialized: true,
  },
  chat: {
    chatStyle: "better_chat",
    width: 218,
    height: 457,
    font: "Arial, Helvetica, sans-serif",
    fontSize: 13,
    usernameSize: 13,
    glow: "#0e5997",
    username: "#ffb020",
    text: "#f4f7ff",
    bubble: "#0a1a33",
    panel: "#061126",
    panelHi: "#0c1c40",
    panelLo: "#081228",
    cardLo: "#0a1836",
    borderColor: "#2f63c9",
    animation: "slide-up",
    flow: "bottom-to-top",
    stagger: 80,
    entry: "bottom",
    autoFade: false,
    lifespan: "persistent",
    fadeAfter: 2,
    maxMessages: 6,
    live: false,
    showHeaderName: false,
    showLiveLabel: false,
    showViewerCount: false,
    viewerCount: 1250,
    bttvEnabled: true,
    bttvGlobal: true,
    bttvChannel: true,
    bttvSize: 2,
    bg: "solid",
    texture: "none",
    textureStrength: 30,
    celebrations: { raid: true, sub: true, gift: true, intensity: 1 },
    showRoleBadges: true,
    roleEffects: {
      enabled: true,
      ownerEnabled: true,
      ownerMovementEnabled: true,
      moderatorEnabled: true,
      moderatorMovementEnabled: true,
      vipEnabled: true,
      vipMovementEnabled: true,
      subscriberEnabled: true,
      subscriberMovementEnabled: true,
      intensity: 8,
      ownerColor: "#ff3b5c",
      moderatorColor: "#22d3ee",
      vipColor: "#c084fc",
      subscriberColor: "#facc15",
      raidColor: "#ff2d8d",
    },
    shoutoutInChat: false,
    shoutoutPosition: "top",
    shoutoutHeight: 180,
    shoutoutDuration: 45,
    shoutoutDismissOnClipEnd: false,
    showEmptyState: false,
    emptyMessage: "Hey you dont you think this chat its too quiet ?",
  },
  rtp_stats: {
    displayStyle: "better_rtp",
    providerMode: "image",
    logoFit: "contain",
    logoHeight: 43,
    logoMaxW: 144,
    logoPadX: 0,
    logoPadY: 0,
    logoOffsetX: 0,
    logoOffsetY: -2,
    showEmblem: false,
    showDividers: false,
    showRtp: true,
    showPotential: true,
    showVolatility: true,
    showBestWin: true,
    cRim: "#1385e9",
    cBarTop: "#0a2140",
    cBarMid: "#07182f",
    cBarBot: "#061126",
    cLabel: "#8baacf",
    cValue: "#ffffff",
    cBolt: "#ffb020",
    cGold: "#ffb020",
    cBrand: "#8baacf",
    cEmA: "#20d8ff",
    cEmB: "#ffb020",
    cEmBase: "#0a1a33",
    fontTitle: "'Barlow', sans-serif",
    fontBody: "'Barlow', sans-serif",
    titleSize: 20,
    titleTracking: 0,
    valueSize: 15,
    labelSize: 15,
    barHeight: 54,
    radius: 17,
    borderWidth: 1,
    barPadX: 20,
    barPadY: 11,
    emblem: "reel",
    emblemSize: 28,
    emblemSpeed: 1,
    emblemStroke: 2,
    emblemAnimate: false,
  },
  background: {
    displayStyle: "better_background",
    bgMode: "texture",
    texture: "aurora",
    color1: "#0a1935",
    color2: "#0d5392",
    color3: "#f18e04",
    intensity: 70,
    animSpeed: 13,
    opacity: 100,
    overlayColor: "#1c1c1c",
    overlayOpacity: 18,
    imageUrl: "",
    videoUrl: "",
    imageFit: "cover",
    imagePosition: "center",
    mediaOpacity: 88,
    brightness: 100,
    contrast: 100,
    saturation: 100,
    blur: 0,
    hueRotate: 0,
    grayscale: 0,
    sepia: 0,
    fxParticles: true,
    fxScanlines: false,
    fxVignette: false,
  },
  slideshow_frame: {
    displayStyle: "better_slideshow_frame",
    mediaText: "/banner.png|image|Banner",
    frameStyle: "neon",
    frameColor: "#0e5391",
    accentColor: "#ffb020",
    backgroundColor: "#020817",
    panelHi: "#0c1c40",
    panelLo: "#081228",
    fit: "cover",
    transition: "fade",
    slideMs: 5000,
    transitionMs: 650,
    autoplay: true,
    videoMuted: true,
    videoLoop: true,
    showVideoControls: false,
    showCounter: false,
    radius: 15,
    borderWidth: 2,
    padding: 12,
    glow: 85,
    aspectPreset: "banner",
  },
  bets: {
    displayStyle: "better_bets",
    theme: "neon",
    font: "cyber",
    fontScale: 100,
    borderRadius: 17,
    glowIntensity: 0,
    opacity: 100,
    fillStyle: "plasma",
    fillSpeed: 120,
    showBrackets: false,
    showSheen: true,
    layoutMode: "bars",
    columns: 2,
    orientation: "horizontal",
    cardColors: [
      { accent: "#20d8ff", accent2: "#67e8f9" },
      { accent: "#1385e9", accent2: "#38bdf8" },
      { accent: "#14b8a6", accent2: "#5eead4" },
      { accent: "#ffb020", accent2: "#ffd166" },
      { accent: "#2563eb", accent2: "#60a5fa" },
      { accent: "#0891b2", accent2: "#22d3ee" },
    ],
  },
});
