import {
  ANIMATION_OPTIONS,
  BORDER_STYLE_OPTIONS,
  COMMON_SETTING_GROUPS,
  FONT_FAMILY_OPTIONS,
  FONT_WEIGHT_OPTIONS,
  IMAGE_FIT_OPTIONS,
  SETTING_TYPES,
  TEXT_ALIGN_OPTIONS,
  TEXT_TRANSFORM_OPTIONS,
  defineSetting,
} from '../shared/settings/settingTypes.js';

export const statisticCardV2Schema = Object.freeze([
  defineSetting({
    key: 'content.header',
    type: SETTING_TYPES.TEXT,
    label: 'Header text',
    description: 'Short title shown above the main value.',
    defaultValue: 'Session Profit',
    group: COMMON_SETTING_GROUPS.CONTENT,
    target: 'header',
    cssVariable: null,
  }),
  defineSetting({
    key: 'content.value',
    type: SETTING_TYPES.TEXT,
    label: 'Main value',
    description: 'The large statistic shown in the card.',
    defaultValue: '+\u20ac1,254.50',
    group: COMMON_SETTING_GROUPS.CONTENT,
    target: 'value',
  }),
  defineSetting({
    key: 'content.secondaryLabel',
    type: SETTING_TYPES.TEXT,
    label: 'Secondary label',
    description: 'Small helper text below the value.',
    defaultValue: 'Above target',
    group: COMMON_SETTING_GROUPS.CONTENT,
    target: 'secondaryLabel',
  }),
  defineSetting({
    key: 'content.icon',
    type: SETTING_TYPES.TEXT,
    label: 'Icon',
    description: 'Emoji or short symbol shown on the card.',
    defaultValue: '\u2197',
    group: COMMON_SETTING_GROUPS.CONTENT,
    target: 'icon',
  }),
  defineSetting({
    key: 'typography.fontFamily',
    type: SETTING_TYPES.SELECT,
    label: 'Font family',
    description: 'Readable font used by the card.',
    defaultValue: FONT_FAMILY_OPTIONS[0].value,
    options: FONT_FAMILY_OPTIONS,
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'root',
    cssVariable: '--stat-card-font-family',
    responsive: true,
  }),
  defineSetting({
    key: 'typography.headerFontSize',
    type: SETTING_TYPES.NUMBER,
    label: 'Header font size',
    description: 'Changes only the header text.',
    defaultValue: 15,
    min: 10,
    max: 48,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'header',
    cssVariable: '--stat-card-header-font-size',
    responsive: true,
  }),
  defineSetting({
    key: 'typography.valueFontSize',
    type: SETTING_TYPES.NUMBER,
    label: 'Value font size',
    description: 'Changes only the large main value.',
    defaultValue: 34,
    min: 16,
    max: 96,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'value',
    cssVariable: '--stat-card-value-font-size',
    responsive: true,
  }),
  defineSetting({
    key: 'typography.labelFontSize',
    type: SETTING_TYPES.NUMBER,
    label: 'Label font size',
    description: 'Changes only the smaller secondary label.',
    defaultValue: 13,
    min: 9,
    max: 36,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'secondaryLabel',
    cssVariable: '--stat-card-label-font-size',
    responsive: true,
  }),
  defineSetting({
    key: 'typography.fontWeight',
    type: SETTING_TYPES.SELECT,
    label: 'Text weight',
    description: 'Controls the default card text weight.',
    defaultValue: 700,
    options: FONT_WEIGHT_OPTIONS,
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'root',
    cssVariable: '--stat-card-font-weight',
  }),
  defineSetting({
    key: 'typography.lineHeight',
    type: SETTING_TYPES.NUMBER,
    label: 'Line height',
    description: 'Vertical rhythm for text.',
    defaultValue: 1.15,
    min: 0.9,
    max: 2,
    step: 0.05,
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'root',
    cssVariable: '--stat-card-line-height',
    responsive: true,
  }),
  defineSetting({
    key: 'typography.letterSpacing',
    type: SETTING_TYPES.NUMBER,
    label: 'Letter spacing',
    description: 'Extra spacing between letters.',
    defaultValue: 0,
    min: 0,
    max: 4,
    step: 0.1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'root',
    cssVariable: '--stat-card-letter-spacing',
  }),
  defineSetting({
    key: 'typography.textTransform',
    type: SETTING_TYPES.SELECT,
    label: 'Text transform',
    description: 'Optional capitalization style.',
    defaultValue: 'none',
    options: TEXT_TRANSFORM_OPTIONS,
    group: COMMON_SETTING_GROUPS.TYPOGRAPHY,
    target: 'root',
    cssVariable: '--stat-card-text-transform',
  }),
  defineSetting({
    key: 'layout.textAlign',
    type: SETTING_TYPES.SELECT,
    label: 'Text alignment',
    description: 'Horizontal alignment for text.',
    defaultValue: 'left',
    options: TEXT_ALIGN_OPTIONS,
    group: COMMON_SETTING_GROUPS.LAYOUT,
    target: 'root',
    cssVariable: '--stat-card-text-align',
  }),
  defineSetting({
    key: 'colors.header',
    type: SETTING_TYPES.COLOR,
    label: 'Header color',
    description: 'Color for the header text only.',
    defaultValue: '#d7f7ff',
    group: COMMON_SETTING_GROUPS.COLORS,
    target: 'header',
    cssVariable: '--stat-card-header-color',
  }),
  defineSetting({
    key: 'colors.value',
    type: SETTING_TYPES.COLOR,
    label: 'Value color',
    description: 'Color for the main value only.',
    defaultValue: '#5eead4',
    group: COMMON_SETTING_GROUPS.COLORS,
    target: 'value',
    cssVariable: '--stat-card-value-color',
  }),
  defineSetting({
    key: 'colors.secondaryLabel',
    type: SETTING_TYPES.COLOR,
    label: 'Secondary label color',
    description: 'Color for the small label only.',
    defaultValue: '#9fb7c8',
    group: COMMON_SETTING_GROUPS.COLORS,
    target: 'secondaryLabel',
    cssVariable: '--stat-card-label-color',
  }),
  defineSetting({
    key: 'colors.icon',
    type: SETTING_TYPES.COLOR,
    label: 'Icon color',
    description: 'Color for the icon.',
    defaultValue: '#facc15',
    group: COMMON_SETTING_GROUPS.COLORS,
    target: 'icon',
    cssVariable: '--stat-card-icon-color',
  }),
  defineSetting({
    key: 'background.color',
    type: SETTING_TYPES.COLOR,
    label: 'Background color',
    description: 'Main card background.',
    defaultValue: '#101827',
    group: COMMON_SETTING_GROUPS.BACKGROUND,
    target: 'root',
    cssVariable: '--stat-card-bg',
  }),
  defineSetting({
    key: 'background.opacity',
    type: SETTING_TYPES.RANGE,
    label: 'Background opacity',
    description: 'Transparency for the card surface.',
    defaultValue: 0.9,
    min: 0,
    max: 1,
    step: 0.05,
    group: COMMON_SETTING_GROUPS.BACKGROUND,
    target: 'root',
    cssVariable: '--stat-card-bg-opacity',
  }),
  defineSetting({
    key: 'border.color',
    type: SETTING_TYPES.COLOR,
    label: 'Border color',
    description: 'Card border color.',
    defaultValue: '#2dd4bf',
    group: COMMON_SETTING_GROUPS.BORDER,
    target: 'root',
    cssVariable: '--stat-card-border-color',
  }),
  defineSetting({
    key: 'border.width',
    type: SETTING_TYPES.NUMBER,
    label: 'Border width',
    description: 'Thickness of the card border.',
    defaultValue: 1,
    min: 0,
    max: 12,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.BORDER,
    target: 'root',
    cssVariable: '--stat-card-border-width',
  }),
  defineSetting({
    key: 'border.style',
    type: SETTING_TYPES.SELECT,
    label: 'Border style',
    description: 'Visual border style.',
    defaultValue: 'solid',
    options: BORDER_STYLE_OPTIONS,
    group: COMMON_SETTING_GROUPS.BORDER,
    target: 'root',
    cssVariable: '--stat-card-border-style',
  }),
  defineSetting({
    key: 'border.radius',
    type: SETTING_TYPES.NUMBER,
    label: 'Border radius',
    description: 'Corner roundness.',
    defaultValue: 18,
    min: 0,
    max: 80,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.BORDER,
    target: 'root',
    cssVariable: '--stat-card-border-radius',
    responsive: true,
  }),
  defineSetting({
    key: 'effects.shadow',
    type: SETTING_TYPES.SELECT,
    label: 'Shadow',
    description: 'Depth under the card.',
    defaultValue: 'medium',
    options: [
      { value: 'none', label: 'None' },
      { value: 'soft', label: 'Soft' },
      { value: 'medium', label: 'Medium' },
      { value: 'strong', label: 'Strong' },
    ],
    group: COMMON_SETTING_GROUPS.EFFECTS,
    target: 'root',
  }),
  defineSetting({
    key: 'effects.glow',
    type: SETTING_TYPES.SELECT,
    label: 'Glow',
    description: 'Accent glow around the border.',
    defaultValue: 'subtle',
    options: [
      { value: 'none', label: 'None' },
      { value: 'subtle', label: 'Subtle' },
      { value: 'medium', label: 'Medium' },
      { value: 'strong', label: 'Strong' },
    ],
    group: COMMON_SETTING_GROUPS.EFFECTS,
    target: 'root',
  }),
  defineSetting({
    key: 'layout.width',
    type: SETTING_TYPES.NUMBER,
    label: 'Width',
    description: 'Card width.',
    defaultValue: 360,
    min: 180,
    max: 900,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.LAYOUT,
    target: 'root',
    cssVariable: '--stat-card-width',
    responsive: true,
  }),
  defineSetting({
    key: 'layout.minHeight',
    type: SETTING_TYPES.NUMBER,
    label: 'Minimum height',
    description: 'Smallest card height.',
    defaultValue: 190,
    min: 120,
    max: 600,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.LAYOUT,
    target: 'root',
    cssVariable: '--stat-card-min-height',
    responsive: true,
  }),
  defineSetting({
    key: 'layout.padding',
    type: SETTING_TYPES.NUMBER,
    label: 'Padding',
    description: 'Space inside the card.',
    defaultValue: 22,
    min: 0,
    max: 80,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.LAYOUT,
    target: 'root',
    cssVariable: '--stat-card-padding',
    responsive: true,
  }),
  defineSetting({
    key: 'layout.gap',
    type: SETTING_TYPES.NUMBER,
    label: 'Gap',
    description: 'Space between card sections.',
    defaultValue: 12,
    min: 0,
    max: 60,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.LAYOUT,
    target: 'root',
    cssVariable: '--stat-card-gap',
    responsive: true,
  }),
  defineSetting({
    key: 'icon.visible',
    type: SETTING_TYPES.BOOLEAN,
    label: 'Show icon',
    description: 'Toggle the top icon.',
    defaultValue: true,
    group: COMMON_SETTING_GROUPS.VISIBILITY,
    target: 'icon',
  }),
  defineSetting({
    key: 'icon.size',
    type: SETTING_TYPES.NUMBER,
    label: 'Icon size',
    description: 'Size of the optional icon.',
    defaultValue: 42,
    min: 14,
    max: 120,
    step: 1,
    unit: 'px',
    group: COMMON_SETTING_GROUPS.IMAGES,
    target: 'icon',
    cssVariable: '--stat-card-icon-size',
    responsive: true,
  }),
  defineSetting({
    key: 'icon.fit',
    type: SETTING_TYPES.SELECT,
    label: 'Icon fit',
    description: 'Fit behavior when an image icon is used later.',
    defaultValue: 'contain',
    options: IMAGE_FIT_OPTIONS,
    group: COMMON_SETTING_GROUPS.IMAGES,
    target: 'icon',
  }),
  defineSetting({
    key: 'progress.visible',
    type: SETTING_TYPES.BOOLEAN,
    label: 'Show progress bar',
    description: 'Toggle the progress bar.',
    defaultValue: true,
    group: COMMON_SETTING_GROUPS.PROGRESS,
    target: 'progress',
  }),
  defineSetting({
    key: 'progress.value',
    type: SETTING_TYPES.RANGE,
    label: 'Progress value',
    description: 'Progress bar fill.',
    defaultValue: 76,
    min: 0,
    max: 100,
    step: 1,
    unit: '%',
    group: COMMON_SETTING_GROUPS.PROGRESS,
    target: 'progress',
  }),
  defineSetting({
    key: 'progress.fillColor',
    type: SETTING_TYPES.COLOR,
    label: 'Progress color',
    description: 'Progress bar fill color.',
    defaultValue: '#5eead4',
    group: COMMON_SETTING_GROUPS.PROGRESS,
    target: 'progress',
    cssVariable: '--stat-card-progress-fill',
  }),
  defineSetting({
    key: 'progress.trackColor',
    type: SETTING_TYPES.COLOR,
    label: 'Progress track',
    description: 'Progress bar track color.',
    defaultValue: '#1e293b',
    group: COMMON_SETTING_GROUPS.PROGRESS,
    target: 'progress',
    cssVariable: '--stat-card-progress-track',
  }),
  defineSetting({
    key: 'animation.type',
    type: SETTING_TYPES.SELECT,
    label: 'Animation',
    description: 'Entrance or idle animation.',
    defaultValue: 'fade',
    options: ANIMATION_OPTIONS,
    group: COMMON_SETTING_GROUPS.ANIMATION,
    target: 'root',
  }),
  defineSetting({
    key: 'animation.speed',
    type: SETTING_TYPES.NUMBER,
    label: 'Animation speed',
    description: 'Transition duration in milliseconds.',
    defaultValue: 280,
    min: 80,
    max: 2000,
    step: 10,
    unit: 'ms',
    group: COMMON_SETTING_GROUPS.ANIMATION,
    target: 'root',
    cssVariable: '--stat-card-transition',
  }),
]);

export default statisticCardV2Schema;
